In [3]:
import pandas as pd
import numpy as np
x=np.random.rand(3,4).round(2)
df = pd.DataFrame(x, columns=['a','b','c','d'])
df

a     b     c     d
0  0.48  0.05  0.59  0.78
1  0.35  0.02  1.00  0.71
2  0.57  0.03  0.20  0.77

## 결측치 처리

In [4]:
df.loc[1]['b']=np.nan

In [5]:
df

a     b     c     d
0  0.48  0.05  0.59  0.78
1  0.35   NaN  1.00  0.71
2  0.57  0.03  0.20  0.77

In [6]:
df.isnull()

a      b      c      d
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False

In [7]:
# 행 삭제하기
cleaned = df.dropna(); cleaned

a     b     c     d
0  0.48  0.05  0.59  0.78
2  0.57  0.03  0.20  0.77

In [8]:
# 평균값넣기
df[df.isnull()] = df.mean(0)['b'] ; df

a     b     c     d
0  0.48  0.05  0.59  0.78
1  0.35  0.04  1.00  0.71
2  0.57  0.03  0.20  0.77

In [9]:
df.loc[1]['b']=np.nan; df

a     b     c     d
0  0.48  0.05  0.59  0.78
1  0.35   NaN  1.00  0.71
2  0.57  0.03  0.20  0.77

In [10]:
df.fillna(method='ffill')

a     b     c     d
0  0.48  0.05  0.59  0.78
1  0.35  0.05  1.00  0.71
2  0.57  0.03  0.20  0.77

# 연습장


In [25]:
import pandas as pd
import numpy as np
x=np.random.rand(3,4).round(2)  #round(2): 소수점 둘째 자리까지
df = pd.DataFrame(x, columns=['a','b','c','d'])
df

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15  0.20  0.98  0.98
2  0.06  0.86  0.82  0.07

In [35]:
# 결측치 처리
df.loc[1]['b']=np.nan

In [27]:
df

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15   NaN  0.98  0.98
2  0.06  0.86  0.82  0.07

In [28]:
df.isnull()

a      b      c      d
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False

In [29]:
# 행 삭제하기
cleaned = df.dropna(); cleaned

a     b     c     d
0  0.21  0.98  0.17  0.79
2  0.06  0.86  0.82  0.07

In [30]:
df

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15   NaN  0.98  0.98
2  0.06  0.86  0.82  0.07

In [31]:
# 평균값 넣기
df[df.isnull()] = df.mean(0)['b'] ; df

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15  0.92  0.98  0.98
2  0.06  0.86  0.82  0.07

In [34]:
df.fillna(method='ffill') #결측값, 앞의 값으로 채워넣다

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15  0.98  0.98  0.98
2  0.06  0.86  0.82  0.07

In [36]:
df.fillna(method='bfill') #결측값, 뒤의 값으로 채워넣다

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15  0.86  0.98  0.98
2  0.06  0.86  0.82  0.07

In [37]:
df #여전히 결측값이 있다,fillna 구문은 결측값을 다른 값으로 채우는 걸 보여준다는 뜻이지, 저장한다는 의미는 아니다

a     b     c     d
0  0.21  0.98  0.17  0.79
1  0.15   NaN  0.98  0.98
2  0.06  0.86  0.82  0.07

In [21]:
Df = df.fillna(method='bfill')  #저장하려면 이런식으로

In [22]:
Df

a     b     c     d
0  0.65  0.45  0.69  0.99
1  0.46  0.64  0.03  0.59
2  0.39  0.83  0.96  0.37

In [23]:
fa=np.random.rand(3,4).round(2);fa

array([[0.14, 0.28, 0.69, 0.75],
       [0.93, 0.67, 0.29, 0.97],
       [0.52, 0.94, 0.26, 0.69]])

In [24]:
fa[1][2] =np.nan
print(fa)


[[0.14 0.28 0.69 0.75]
 [0.93 0.67  nan 0.97]
 [0.52 0.94 0.26 0.69]]
